# Site settings
permalink: pretty
baseurl:   "" # the subpath of your site, e.g. /blog
url:       "http://mbmosman.github.io"


title:     Mary Mosman
tagline:   Software Engineer & Instructor
description: >- # this means to ignore newlines until "baseurl:"
  I’ve worked as developer since the 90's, but teaching programming & web development
  to others has become what I'm passionate about. I’ve taught people of all ages through 
  formal college classes, corporate training, and less formal gatherings & meet-ups.  
  Outside of tech, I have a love of languages and maps. While I long to travel more of 
  the real world some day, I currently spend more time journeying through imaginary 
  locations from books, games, and anime. My current project is the creation of my own 
  imaginary world of Atmina.

# Social
twitter_username: mbmosman
github_username:  mbmosman
linkedin: mary-mosman

# Build settings
markdown: kramdown
theme: minima
paginate_path: "/blog/page:num/"
paginate: 1

# This will require each of these plugins automatically.
plugins:
  - jekyll-feed  
  - jekyll-gist
  - jekyll-paginate





