# Site settings
baseurl:   "" # the subpath of your site, e.g. /blog
url:       "http://mbmosman.github.io"

# Personal Info
title:     Mary Mosman
tagline:   Software Engineer & Instructor
description: >- # this means to ignore newlines 
  I’ve worked as a web developer at many companies throughout the Twin Cities, but teaching 
  programming & web development to others has become what I'm passionate about. I’ve taught 
  people of all ages through formal college classes, corporate training, and less formal 
  gatherings & meet-ups. 


# Blog settings
paginate_path: blog/page/:num/
permalink: pretty
paginate: 8

# Features
rss_enabled: false

# Social
social:
  github: mbmosman
  linkedin: mary-mosman
  twitter: mbmosman
  steam: cuteChickiboo


# This will require each of these plugins automatically.
plugins:
  - jekyll-feed  
  - jekyll-gist
  - jekyll-paginate
  - jekyll-assets

assets:
  source_maps: false
  sources:
    - _assets/icons
    - _assets/images
    - _assets/css

collections:
  book:
    output: true
    permalink: /:collection/:name
  manga:
    output: true
    permalink: /:collection/:name
  vizmedia:
    output: true
    permalink: /:collection/:name
  game:
    output: true
    permalink: /:collection/:name

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: book
    values:
      layout: "book"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: manga
    values:
      layout: "manga"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: vizmedia
    values:
      layout: "vizmedia"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: game
    values:
      layout: "game"

